### ISSUE TITLE
The 4.6 version doesn't find the current MS Build, its always looking for Visual Studio 15.1

### ISSUE THREAD

**Issue by hfickes** [Itiviti/gradle-msbuild-plugin#136]
The 3.15 plug in works fine.  When I use the 4.6 plugin, it complains that it can't find 'Microsoft.Build, Version=15.1.0.0'.

I'm using VS 2022 (Version 17.10) but even when I set the version or msbuildDir variables, the plugin keeps producing the error that it can't find 15.1

**Comment by hfickes** [comment]
Still happening with the 4.7 plugin. Here is the error message:

Could not determine the dependencies of task ':assemblyInfoPatcher'.
> Failed to query the value of task ':assemblyInfoPatcher' property 'projects'.
   > Failed to parse project, exit code: -1, output: ',' error: 'MSBuildLocator cannot detect VS location
     Error was: System.InvalidOperationException: Sequence contains no elements
        at System.Linq.ThrowHelper.ThrowNoElementsException()
        at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
        at ProjectFileParser.MSBuildCustomLocator.Register()
     Error during project file parsing: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
     File name: 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
        at ProjectFileParser.Program.ParseSolution(String file, Dictionary`2 args)
        at ProjectFileParser.Program.Parse(String file, Dictionary`2 args)
        at ProjectFileParser.Program.Main(String[] args)
